spring:
  cloud:
    gateway:
      routes:
      - id: default_path_to_deeplink
        uri: http://httpbin.org/anything
        order: 10000
        predicates:
        - Path=/
        filters:
        - RedirectToPathFromHostName=/website/%s/home,301