pathURI: http://httpbirrn.org/anything
spring:
  cloud:
    gateway:
      routes:
      - id: medialinks_to_mediaserver
        uri: ${pathURI}
        predicates:
        - Path=/media
        filters:
        - AddRequestHeader=X-Request-Example, ValueA

 #      - id: default_path_to_deeplink
#        uri: ${pathURI}
#        predicates:
#        - Path=/
#        filters:
#        - RedirectToPathFromHostName=/website/%s/home,301

